### ISSUE TITLE
Font color change in .active class does not apply

### ISSUE THREAD

**Issue by theresaabl** [theresaabl/pp-seminars#2]
I would like to change the font color when a page in the navigation is active.
I attempt this with the .active class:
```css
.active {
    border-bottom: 1px solid #a8a8ff; 
    color: #a8a8ff;
}
``` 
The border-bottom style does apply, but the font-color does not change.

![image](https://github.com/user-attachments/assets/25ac3e58-cf9a-4c10-93ea-3964935f6519)

**Comment by theresaabl** [comment]
Fixed this by increasing CSS specificity:
```css
#menu a.active {
    border-bottom: 1px solid #a8a8ff; 
    color: #a8a8ff;
}
```
